/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;

import clases.ejercicio1.Ejercicio1C;
import java.util.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author vergo_000
 */
public class Ejercicio1 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio1
     */
    Ejercicio1C n = new Ejercicio1C();

    public Ejercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCantidad = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        cmbDenom = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnTotal = new javax.swing.JButton();
        lblFin = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Billetes/Monedas");
        setName("frmEjercicio1"); // NOI18N

        lblCantidad.setText("Ingrese la cantidad de billetes/monedas:");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        cmbDenom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "$0.01", "$0.05", "$0.10", "$0.25", "$1.00", "$5.00", "$10.00", "$20.00", "$50.00", "$100.00", " " }));

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
        });

        jLabel2.setText("Seleccione la denominacion:");

        btnTotal.setText("Calcular total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        lblFin.setText("Total:");

        lblTotal.setText("T");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidad)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidad)
                            .addComponent(cmbDenom, 0, 110, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnIngresar)
                        .addGap(42, 42, 42)
                        .addComponent(btnTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(lblFin)
                        .addGap(50, 50, 50)
                        .addComponent(lblTotal)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFin)
                    .addComponent(lblTotal))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        int cantidad = Integer.parseInt(txtCantidad.getText().trim());
        if (cantidad > 0) {
            switch (cmbDenom.getSelectedIndex()) {
                case 0:
                    n.agregar(Integer.parseInt(txtCantidad.getText().trim()), 0.01);
                    JOptionPane.showMessageDialog(rootPane, "Cantidad ingresada", "Ingreso correcto", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 1:
                    n.agregar(Integer.parseInt(txtCantidad.getText().trim()), 0.05);
                    JOptionPane.showMessageDialog(rootPane, "Cantidad ingresada", "Ingreso correcto", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 2:
                    n.agregar(Integer.parseInt(txtCantidad.getText().trim()), 0.10);
                    JOptionPane.showMessageDialog(rootPane, "Cantidad ingresada", "Ingreso correcto", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 3:
                    n.agregar(Integer.parseInt(txtCantidad.getText().trim()), 0.25);
                    JOptionPane.showMessageDialog(rootPane, "Cantidad ingresada", "Ingreso correcto", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 4:
                    n.agregar(Integer.parseInt(txtCantidad.getText().trim()), 1);
                    JOptionPane.showMessageDialog(rootPane, "Cantidad ingresada", "Ingreso correcto", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 5:
                    n.agregar(Integer.parseInt(txtCantidad.getText().trim()), 5);
                    JOptionPane.showMessageDialog(rootPane, "Cantidad ingresada", "Ingreso correcto", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 6:
                    n.agregar(Integer.parseInt(txtCantidad.getText().trim()), 10);
                    JOptionPane.showMessageDialog(rootPane, "Cantidad ingresada", "Ingreso correcto", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 7:
                    n.agregar(Integer.parseInt(txtCantidad.getText().trim()), 20);
                    JOptionPane.showMessageDialog(rootPane, "Cantidad ingresada", "Ingreso correcto", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 8:
                    n.agregar(Integer.parseInt(txtCantidad.getText().trim()), 50);
                    JOptionPane.showMessageDialog(rootPane, "Cantidad ingresada", "Ingreso correcto", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 9:
                    n.agregar(Integer.parseInt(txtCantidad.getText().trim()), 100);
                    JOptionPane.showMessageDialog(rootPane, "Cantidad ingresada", "Ingreso correcto", JOptionPane.INFORMATION_MESSAGE);
                    break;

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ingresa solo numeros enteros", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        // TODO add your handling code here:
      String numeros="1234567890-";
      if(numeros.contains(evt.getKeyChar()+""))
      {
      }
      else
      {
          txtCantidad.setText("");
      }

    }//GEN-LAST:event_txtCantidadKeyPressed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        double total = n.calcular();
        String fin = String.valueOf(total);
        lblTotal.setText(fin);
        n.limpiar();
    }//GEN-LAST:event_btnTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cmbDenom;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblFin;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
